title: TriangleCrypto.com
description: For the crypto community in the Raleigh, Durham, and Chapel Hill area.
header_links:
  newsletter: 'http://ok.com'
  discord: 'https://discord.gg/JB3e685PSK'
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman